run-name: 'Repository Sync'
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: 'vergilcw/dotfiles'
          source_branch: 'main'
          destination_branch: 'main'
          github_token: ${{ secrets.PAT }}
